# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache pm2
      id: cache-pm2
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: pm2-${{ runner.os }}-pm2
        restore-keys: |
          pm2-${{ runner.os }}-

    - name: Install pm2 if not cached
      run: npm install -g pm2
      if: steps.cache-pm2.outputs.cache-hit != 'true'

    - name: Install dependencies
      run: npm ci

    - name: List files in repository root
      run: ls -la

    - name: Pull latest changes from repository
      run: git pull
      working-directory: ./crud-postman-mongodb

    - name: Restart server with pm2
      run: pm2 restart server
      working-directory: ./crud-postman-mongodb

    - name: Restart Caddy
      run: sudo systemctl restart caddy
